########################
#
#  Some semantics/things to note:
#  - To simplify/reduce topics names, every "level" can have a "topic" which gets appended to the previous level.
#    If a level doesn't have a "topic", or levels inbetween that don't have topics, nothing gets appended.
#      -- I'm not sure if "topic" is the best word choice, but...
#
#  - The "top" level is really about configuring the EVB/INS, subsequent levels are "object-specific" configuration.
#    In most cases, these "objects" are essentially sensor, or peripheral-specific, ie, gps1, or evb_radio.
#    Everything that is related to that "object" should be underneath that level, creating additional levels if needed.
#    Sensor objects (ins, gps1, mag, etc) will have either a "message" or a "messages" sublevel.
#    Message means there is only 1 message published for that object, and does not define a "type".
#    Messages is used when more than one message type can be published, and the label for the subsequent level is
#    the message type. Messages can have sublevels, with each type being nested under its parent type.
#
#  - There are some things that I didn't know where to put, but I think its getting close
#
#  - We will assume defaults for all parameters, and the 'example.yaml' outlines those defaults. Anything that is
#    using the default value should be commented out. As such, the actual example.yaml will have most every line
#    commented out... I think the only exception is the top-level port... and even it *could* have a default.
#
#  - each "Message" or "Messages" nodes have a "topic" element. Should this topic value default to the coded value,
#    or can it default to the parent node's name?  (ie, "raw/topic" will default to "raw".)
#
#  - I've called out specific things with FIXME's.  These should highlight in your IDE.
#
########################


topic: "inertialsense"
port: [/dev/ttyACM0, /dev/ttyACM1]
baudrate: 921600
enable_log: false
publishTf: true                                 # Publish Transform Frame (TR)
frame_id: ""                                    # FIXME: What is this?  is it just the FrameID to use in the ROS messages?
mag_declination: 0.0
ref_lla: [0.0, 0.0, 0.0]

# Hardware platform specifying the IMX carrier board type (i.e. EVB-2) and configuration bits (see ePlatformConfig).  The platform type is used to simplify the GPS and I/O configuration process.
platformConfig: 4                                # PLATFORM_CFG_TYPE_NONE_ONBOARD_M8

# IMX ioConfig (see eIoConfig)
ioConfig: 0x025ca046
# ioConfig: 0x26CA060       # EVB2: GPS1 Ser1 F9P, GPS2 Ser2 F9P, PPS G8
# ioConfig: 0x025CA060      # EVB2: GPS1 Ser1 F9P, GPS2 Ser0 F9P, PPS G8
# ioConfig: 0x0244a060      # EVB2: GPS1 Ser1 F9P, GPS2 disabled F9P, PPS G8

# Service Points - should we allow these?  Or should they always be hardcoded?
# service_endpoints:
  # REF_LLA: "set_refLLA"                         # /value /current
  # MAG_CAL: "mag_cal"                            # /single /multi
  # FIRMWARE: "firmware"                          # /get /update

# Publish the firmware upgrade progress/status
firmware_status:
  message:
    topic: "firmware_status"
    enable: false

transform_frame:
  # static_transform:
  message:
    topic: ""
    enable: true

ins:
  rotation: [0, 0, 0]                           # Rotation in radians about the X,Y,Z axes from Sensor Frame to Intermediate Output Frame.  Order applied: Z,Y,X.
  offset: [0, 0 ,0]                             # X,Y,Z offset in meters from Intermediate Output Frame to INS Output Frame.
  navigation_dt_ms: 16                          # EKF update period.  IMX-5:  16 default, 8 max.  Use `msg/ins.../period` to reduce INS output data rate.
  dynamic_model: 4                              # FIXME: these should be named types/srtring (PORTABLE, STATIONARY, AGV, UAV, etc)
  enable_covariance: true                       # Include covariance data in odom_ins_... messages
  messages:
    odom_ins_enu:
      topic: "odom_ins_enu"
      enable: true
    odom_ins_ned:
      topic: "odom_ins_ned"
      enable: false
    odom_ins_ecef:
      topic: "odom_ins_ecef"
      enable: false
    did_ins1:
      topic: "ins_eul_uvw_ned"
      enable: false
    did_ins2:
      topic: "ins_quat_uvw_lla"
      enable: false
    did_ins4:
      topic: "ins_quat_ve_ecef"
      enable: false
      period: 50     # if odom_ins_* enabled pimu period will be used
    inl2_states:
      topic: "inl2_states"
      enable: false

sensors:
  messages:  
    imu:              # Publish IMU angular rates and linear acceleration
      topic: "imu"
      enable: false
      period: 1
    pimu:             # Publish preintegrated IMU delta theta and delta velocity
      topic: "pimu"
      enable: false
      period: 1
    magnetometer:
      topic: "mag"
      enable: false
      period: 1
    barometer:
      topic: "baro"
      enable: false
      period: 1
    strobe_in:      # Publish the strobe input time
      topic: "strobe_in"
      enable: true

gps1:
  enabled: false
  type: 'F9P'
  antenna_offset: [-0.005, 0.206, 0]                     # X,Y,Z offset in meters in Sensor Frame to GPS 1 antenna
  gpsTimeUserDelay: 0.0
  messages:
    pos_vel:
      topic: "gps1/pos_vel"
      enable: false
      period: 1
    navsatfix:
      topic: "/NavSatFix"                        # /navsatfix
      enable: false
    info:
      topic: "gps1/info"                        # inertialsense/gps1/info
      enable: false
      period: 5                                 # Publish every 1 second (200ms x 5)
    raw:
      topic: "gps1/raw"                         # Observation "/obs", ephemeris "/eph", and GLONASS ephemeris "/gep" are appended to the end of the topic name.  (i.e. topic="gps1_raw" results is "gps1_raw_obs" published as actual topic)
      enable: false
      period: 5                                 # Publish every 1 second (200ms x 5)
    rtk_pos_rel:
      topic: "gps1/pos_vel"
      enable: false
      period: 1
    rel:
      enable: true
      topic: "rel"
    base:
      topic: "base"
      rel:
        topic: "rel"
      info:
        topic: "info"
    compass:
      topic: "compass"
      rel:
        topic: "rel"
      info:
        topic: "info"

gps2:
  enabled: false
  type: 'M8'
  antenna_offset: [-0.005, -0.206, 0]                     # X,Y,Z offset in meters in Sensor Frame to GPS 1 antenna
  gpsTimeUserDelay: 0.0
  messages:
    pos_vel:
      topic: "gps2/pos_vel"
      enable: false
      period: 1
    navsatfix:
      topic: "/NavSatFix"                        # /navsatfix
      enable: false
    info:
      topic: "gps2/info"                        # inertialsense/gps1/info
      enable: false
      period: 5                                 # Publish every 1 second (200ms x 5)
    raw:
      topic: "gps2/raw"                         # Observation "/obs", ephemeris "/eph", and GLONASS ephemeris "/gep" are appended to the end of the topic name.  (i.e. topic="gps1_raw" results is "gps1_raw_obs" published as actual topic)
      enable: false
      period: 5                                 # Publish every 1 second (200ms x 5)
    rtk_pos_rel:
      topic: "gps2/rtk_rel_pos"
      enable: false
      period: 1
    rel:
      enable: false
      topic: "rel"
    base:
      topic: "base"
      rel:
        topic: "rel"
      info:
        topic: "info"
    compass:
      topic: "compass"
      rel:
        topic: "rel"
      info:
        topic: "info"

rtk_rover:
  positioning_enable: true                     # Enable RTK precision positioning at GPS1
  compassing_enable: true                      # Enable RTK compassing (dual GNSS moving baseline RTK) at GPS2
  correction_input:
    select: radio                       # Select correction input settings

    radio:
      type: "evb"
      format: RTCM3
      port: "LoRa"
